# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea88f2f8521c8ed2ba38308c1dc5e3b1103f6d01ac21a5bf6ae105f53a5c1a92ef156595c17ede7427677e29a4fbda4a56f7dea2c0bb1199d22f11c33166a8b

test:
  secret_key_base: 01667b642f347ec27cd3a381353825082c6e9392c51357b7491c4bff91f9c8e51175bbb3cd7b2a331ad31809c8405997ffd1940c97086da60d9c9d725376fe6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
